server:
  port: 10010
spring:
  application:
    name: code-generator
  datasource:
    name: test
    url: jdbc:mysql://10.40.66.184:3306/pdm_sbom?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ab123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.curves.service.account.services.pojo.entity
# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mapper:
  plugin: tk.mybatis.mapper.generator.MapperPlugin
  Mapper: tk.mybatis.mapper.common.Mapper
  mappers: com.zte.pdm.codegenerator.commons.mapper.BaseMapper
  not-empty: false
  identity: MYSQL
